# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "build app and upload to testflight"
  lane :beta do
    match(
      type: "appstore"
    )
    # 빌드 버전 향상
    increment_build_number(build_number: latest_testflight_build_number + 1)

    # 앱 빌드
    build_app(scheme: "BestEats")

    # TestFlight 업로드
    upload_to_testflight(
      api_key: app_store_connect_api_key(
        key_id: ENV["KEY_ID"],
        issuer_id: ENV["ISSUER_ID"],
        key_content: ENV["API_KEY_CONTENT"]
      )
    )

    # add actions here: https://docs.fastlane.tools/actions
  end
end
